// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
// NOTE (not part of drift_dev's own output): hand-authored by mirroring
// schema_v3.dart's shape for the sandbox that produced it, which has no
// Flutter/Dart toolchain to actually run `dart run drift_dev schema dump`
// / `schema generate`. Regenerate for real before relying on this file:
//   dart run drift_dev schema dump lib/data/drift/database.dart drift_schemas/
//   dart run drift_dev schema generate --data-classes --companions drift_schemas/ test/generated_migrations/
// and diff the result against this file and drift_schemas/drift_schema_v4.json.
import 'package:drift/drift.dart';

class SelectedQuestRows extends Table
    with TableInfo<SelectedQuestRows, SelectedQuestRowsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SelectedQuestRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> journeyId = GeneratedColumn<String>(
    'journey_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> startedAt = GeneratedColumn<String>(
    'started_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [ownerId, journeyId, startedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'selected_quest_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId};
  @override
  SelectedQuestRowsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SelectedQuestRowsData(
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      journeyId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}journey_id'],
      )!,
      startedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}started_at'],
      )!,
    );
  }

  @override
  SelectedQuestRows createAlias(String alias) {
    return SelectedQuestRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(owner_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class SelectedQuestRowsData extends DataClass
    implements Insertable<SelectedQuestRowsData> {
  final String ownerId;
  final String journeyId;
  final String startedAt;
  const SelectedQuestRowsData({
    required this.ownerId,
    required this.journeyId,
    required this.startedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['owner_id'] = Variable<String>(ownerId);
    map['journey_id'] = Variable<String>(journeyId);
    map['started_at'] = Variable<String>(startedAt);
    return map;
  }

  SelectedQuestRowsCompanion toCompanion(bool nullToAbsent) {
    return SelectedQuestRowsCompanion(
      ownerId: Value(ownerId),
      journeyId: Value(journeyId),
      startedAt: Value(startedAt),
    );
  }

  factory SelectedQuestRowsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SelectedQuestRowsData(
      ownerId: serializer.fromJson<String>(json['ownerId']),
      journeyId: serializer.fromJson<String>(json['journeyId']),
      startedAt: serializer.fromJson<String>(json['startedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'ownerId': serializer.toJson<String>(ownerId),
      'journeyId': serializer.toJson<String>(journeyId),
      'startedAt': serializer.toJson<String>(startedAt),
    };
  }

  SelectedQuestRowsData copyWith({
    String? ownerId,
    String? journeyId,
    String? startedAt,
  }) => SelectedQuestRowsData(
    ownerId: ownerId ?? this.ownerId,
    journeyId: journeyId ?? this.journeyId,
    startedAt: startedAt ?? this.startedAt,
  );
  SelectedQuestRowsData copyWithCompanion(SelectedQuestRowsCompanion data) {
    return SelectedQuestRowsData(
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      journeyId: data.journeyId.present ? data.journeyId.value : this.journeyId,
      startedAt: data.startedAt.present ? data.startedAt.value : this.startedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('SelectedQuestRowsData(')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('startedAt: $startedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(ownerId, journeyId, startedAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SelectedQuestRowsData &&
          other.ownerId == this.ownerId &&
          other.journeyId == this.journeyId &&
          other.startedAt == this.startedAt);
}

class SelectedQuestRowsCompanion
    extends UpdateCompanion<SelectedQuestRowsData> {
  final Value<String> ownerId;
  final Value<String> journeyId;
  final Value<String> startedAt;
  final Value<int> rowid;
  const SelectedQuestRowsCompanion({
    this.ownerId = const Value.absent(),
    this.journeyId = const Value.absent(),
    this.startedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  SelectedQuestRowsCompanion.insert({
    required String ownerId,
    required String journeyId,
    required String startedAt,
    this.rowid = const Value.absent(),
  }) : ownerId = Value(ownerId),
       journeyId = Value(journeyId),
       startedAt = Value(startedAt);
  static Insertable<SelectedQuestRowsData> custom({
    Expression<String>? ownerId,
    Expression<String>? journeyId,
    Expression<String>? startedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (ownerId != null) 'owner_id': ownerId,
      if (journeyId != null) 'journey_id': journeyId,
      if (startedAt != null) 'started_at': startedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  SelectedQuestRowsCompanion copyWith({
    Value<String>? ownerId,
    Value<String>? journeyId,
    Value<String>? startedAt,
    Value<int>? rowid,
  }) {
    return SelectedQuestRowsCompanion(
      ownerId: ownerId ?? this.ownerId,
      journeyId: journeyId ?? this.journeyId,
      startedAt: startedAt ?? this.startedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (journeyId.present) {
      map['journey_id'] = Variable<String>(journeyId.value);
    }
    if (startedAt.present) {
      map['started_at'] = Variable<String>(startedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('SelectedQuestRowsCompanion(')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('startedAt: $startedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class StepIntervalRecords extends Table
    with TableInfo<StepIntervalRecords, StepIntervalRecordsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  StepIntervalRecords(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> journeyId = GeneratedColumn<String>(
    'journey_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> intervalStart = GeneratedColumn<String>(
    'interval_start',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> intervalEnd = GeneratedColumn<String>(
    'interval_end',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> steps = GeneratedColumn<int>(
    'steps',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> walkingDistanceMeters = GeneratedColumn<int>(
    'walking_distance_meters',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> resolvedMeters = GeneratedColumn<int>(
    'resolved_meters',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> flaggedPace = GeneratedColumn<int>(
    'flagged_pace',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (flagged_pace IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> syncedAt = GeneratedColumn<String>(
    'synced_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    ownerId,
    journeyId,
    intervalStart,
    intervalEnd,
    steps,
    walkingDistanceMeters,
    resolvedMeters,
    flaggedPace,
    syncedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'step_interval_records';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {ownerId, journeyId, intervalStart},
  ];
  @override
  StepIntervalRecordsData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return StepIntervalRecordsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      journeyId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}journey_id'],
      )!,
      intervalStart: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}interval_start'],
      )!,
      intervalEnd: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}interval_end'],
      )!,
      steps: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}steps'],
      )!,
      walkingDistanceMeters: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}walking_distance_meters'],
      ),
      resolvedMeters: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}resolved_meters'],
      )!,
      flaggedPace: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}flagged_pace'],
      )!,
      syncedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}synced_at'],
      )!,
    );
  }

  @override
  StepIntervalRecords createAlias(String alias) {
    return StepIntervalRecords(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(owner_id, journey_id, interval_start)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class StepIntervalRecordsData extends DataClass
    implements Insertable<StepIntervalRecordsData> {
  final int id;
  final String ownerId;
  final String journeyId;
  final String intervalStart;
  final String intervalEnd;
  final int steps;
  final int? walkingDistanceMeters;
  final int resolvedMeters;
  final int flaggedPace;
  final String syncedAt;
  const StepIntervalRecordsData({
    required this.id,
    required this.ownerId,
    required this.journeyId,
    required this.intervalStart,
    required this.intervalEnd,
    required this.steps,
    this.walkingDistanceMeters,
    required this.resolvedMeters,
    required this.flaggedPace,
    required this.syncedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['owner_id'] = Variable<String>(ownerId);
    map['journey_id'] = Variable<String>(journeyId);
    map['interval_start'] = Variable<String>(intervalStart);
    map['interval_end'] = Variable<String>(intervalEnd);
    map['steps'] = Variable<int>(steps);
    if (!nullToAbsent || walkingDistanceMeters != null) {
      map['walking_distance_meters'] = Variable<int>(walkingDistanceMeters);
    }
    map['resolved_meters'] = Variable<int>(resolvedMeters);
    map['flagged_pace'] = Variable<int>(flaggedPace);
    map['synced_at'] = Variable<String>(syncedAt);
    return map;
  }

  StepIntervalRecordsCompanion toCompanion(bool nullToAbsent) {
    return StepIntervalRecordsCompanion(
      id: Value(id),
      ownerId: Value(ownerId),
      journeyId: Value(journeyId),
      intervalStart: Value(intervalStart),
      intervalEnd: Value(intervalEnd),
      steps: Value(steps),
      walkingDistanceMeters: walkingDistanceMeters == null && nullToAbsent
          ? const Value.absent()
          : Value(walkingDistanceMeters),
      resolvedMeters: Value(resolvedMeters),
      flaggedPace: Value(flaggedPace),
      syncedAt: Value(syncedAt),
    );
  }

  factory StepIntervalRecordsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return StepIntervalRecordsData(
      id: serializer.fromJson<int>(json['id']),
      ownerId: serializer.fromJson<String>(json['ownerId']),
      journeyId: serializer.fromJson<String>(json['journeyId']),
      intervalStart: serializer.fromJson<String>(json['intervalStart']),
      intervalEnd: serializer.fromJson<String>(json['intervalEnd']),
      steps: serializer.fromJson<int>(json['steps']),
      walkingDistanceMeters: serializer.fromJson<int?>(
        json['walkingDistanceMeters'],
      ),
      resolvedMeters: serializer.fromJson<int>(json['resolvedMeters']),
      flaggedPace: serializer.fromJson<int>(json['flaggedPace']),
      syncedAt: serializer.fromJson<String>(json['syncedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'ownerId': serializer.toJson<String>(ownerId),
      'journeyId': serializer.toJson<String>(journeyId),
      'intervalStart': serializer.toJson<String>(intervalStart),
      'intervalEnd': serializer.toJson<String>(intervalEnd),
      'steps': serializer.toJson<int>(steps),
      'walkingDistanceMeters': serializer.toJson<int?>(walkingDistanceMeters),
      'resolvedMeters': serializer.toJson<int>(resolvedMeters),
      'flaggedPace': serializer.toJson<int>(flaggedPace),
      'syncedAt': serializer.toJson<String>(syncedAt),
    };
  }

  StepIntervalRecordsData copyWith({
    int? id,
    String? ownerId,
    String? journeyId,
    String? intervalStart,
    String? intervalEnd,
    int? steps,
    Value<int?> walkingDistanceMeters = const Value.absent(),
    int? resolvedMeters,
    int? flaggedPace,
    String? syncedAt,
  }) => StepIntervalRecordsData(
    id: id ?? this.id,
    ownerId: ownerId ?? this.ownerId,
    journeyId: journeyId ?? this.journeyId,
    intervalStart: intervalStart ?? this.intervalStart,
    intervalEnd: intervalEnd ?? this.intervalEnd,
    steps: steps ?? this.steps,
    walkingDistanceMeters: walkingDistanceMeters.present
        ? walkingDistanceMeters.value
        : this.walkingDistanceMeters,
    resolvedMeters: resolvedMeters ?? this.resolvedMeters,
    flaggedPace: flaggedPace ?? this.flaggedPace,
    syncedAt: syncedAt ?? this.syncedAt,
  );
  StepIntervalRecordsData copyWithCompanion(StepIntervalRecordsCompanion data) {
    return StepIntervalRecordsData(
      id: data.id.present ? data.id.value : this.id,
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      journeyId: data.journeyId.present ? data.journeyId.value : this.journeyId,
      intervalStart: data.intervalStart.present
          ? data.intervalStart.value
          : this.intervalStart,
      intervalEnd: data.intervalEnd.present
          ? data.intervalEnd.value
          : this.intervalEnd,
      steps: data.steps.present ? data.steps.value : this.steps,
      walkingDistanceMeters: data.walkingDistanceMeters.present
          ? data.walkingDistanceMeters.value
          : this.walkingDistanceMeters,
      resolvedMeters: data.resolvedMeters.present
          ? data.resolvedMeters.value
          : this.resolvedMeters,
      flaggedPace: data.flaggedPace.present
          ? data.flaggedPace.value
          : this.flaggedPace,
      syncedAt: data.syncedAt.present ? data.syncedAt.value : this.syncedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('StepIntervalRecordsData(')
          ..write('id: $id, ')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('intervalStart: $intervalStart, ')
          ..write('intervalEnd: $intervalEnd, ')
          ..write('steps: $steps, ')
          ..write('walkingDistanceMeters: $walkingDistanceMeters, ')
          ..write('resolvedMeters: $resolvedMeters, ')
          ..write('flaggedPace: $flaggedPace, ')
          ..write('syncedAt: $syncedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    ownerId,
    journeyId,
    intervalStart,
    intervalEnd,
    steps,
    walkingDistanceMeters,
    resolvedMeters,
    flaggedPace,
    syncedAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is StepIntervalRecordsData &&
          other.id == this.id &&
          other.ownerId == this.ownerId &&
          other.journeyId == this.journeyId &&
          other.intervalStart == this.intervalStart &&
          other.intervalEnd == this.intervalEnd &&
          other.steps == this.steps &&
          other.walkingDistanceMeters == this.walkingDistanceMeters &&
          other.resolvedMeters == this.resolvedMeters &&
          other.flaggedPace == this.flaggedPace &&
          other.syncedAt == this.syncedAt);
}

class StepIntervalRecordsCompanion
    extends UpdateCompanion<StepIntervalRecordsData> {
  final Value<int> id;
  final Value<String> ownerId;
  final Value<String> journeyId;
  final Value<String> intervalStart;
  final Value<String> intervalEnd;
  final Value<int> steps;
  final Value<int?> walkingDistanceMeters;
  final Value<int> resolvedMeters;
  final Value<int> flaggedPace;
  final Value<String> syncedAt;
  const StepIntervalRecordsCompanion({
    this.id = const Value.absent(),
    this.ownerId = const Value.absent(),
    this.journeyId = const Value.absent(),
    this.intervalStart = const Value.absent(),
    this.intervalEnd = const Value.absent(),
    this.steps = const Value.absent(),
    this.walkingDistanceMeters = const Value.absent(),
    this.resolvedMeters = const Value.absent(),
    this.flaggedPace = const Value.absent(),
    this.syncedAt = const Value.absent(),
  });
  StepIntervalRecordsCompanion.insert({
    this.id = const Value.absent(),
    required String ownerId,
    required String journeyId,
    required String intervalStart,
    required String intervalEnd,
    required int steps,
    this.walkingDistanceMeters = const Value.absent(),
    required int resolvedMeters,
    this.flaggedPace = const Value.absent(),
    required String syncedAt,
  }) : ownerId = Value(ownerId),
       journeyId = Value(journeyId),
       intervalStart = Value(intervalStart),
       intervalEnd = Value(intervalEnd),
       steps = Value(steps),
       resolvedMeters = Value(resolvedMeters),
       syncedAt = Value(syncedAt);
  static Insertable<StepIntervalRecordsData> custom({
    Expression<int>? id,
    Expression<String>? ownerId,
    Expression<String>? journeyId,
    Expression<String>? intervalStart,
    Expression<String>? intervalEnd,
    Expression<int>? steps,
    Expression<int>? walkingDistanceMeters,
    Expression<int>? resolvedMeters,
    Expression<int>? flaggedPace,
    Expression<String>? syncedAt,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (ownerId != null) 'owner_id': ownerId,
      if (journeyId != null) 'journey_id': journeyId,
      if (intervalStart != null) 'interval_start': intervalStart,
      if (intervalEnd != null) 'interval_end': intervalEnd,
      if (steps != null) 'steps': steps,
      if (walkingDistanceMeters != null)
        'walking_distance_meters': walkingDistanceMeters,
      if (resolvedMeters != null) 'resolved_meters': resolvedMeters,
      if (flaggedPace != null) 'flagged_pace': flaggedPace,
      if (syncedAt != null) 'synced_at': syncedAt,
    });
  }

  StepIntervalRecordsCompanion copyWith({
    Value<int>? id,
    Value<String>? ownerId,
    Value<String>? journeyId,
    Value<String>? intervalStart,
    Value<String>? intervalEnd,
    Value<int>? steps,
    Value<int?>? walkingDistanceMeters,
    Value<int>? resolvedMeters,
    Value<int>? flaggedPace,
    Value<String>? syncedAt,
  }) {
    return StepIntervalRecordsCompanion(
      id: id ?? this.id,
      ownerId: ownerId ?? this.ownerId,
      journeyId: journeyId ?? this.journeyId,
      intervalStart: intervalStart ?? this.intervalStart,
      intervalEnd: intervalEnd ?? this.intervalEnd,
      steps: steps ?? this.steps,
      walkingDistanceMeters:
          walkingDistanceMeters ?? this.walkingDistanceMeters,
      resolvedMeters: resolvedMeters ?? this.resolvedMeters,
      flaggedPace: flaggedPace ?? this.flaggedPace,
      syncedAt: syncedAt ?? this.syncedAt,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (journeyId.present) {
      map['journey_id'] = Variable<String>(journeyId.value);
    }
    if (intervalStart.present) {
      map['interval_start'] = Variable<String>(intervalStart.value);
    }
    if (intervalEnd.present) {
      map['interval_end'] = Variable<String>(intervalEnd.value);
    }
    if (steps.present) {
      map['steps'] = Variable<int>(steps.value);
    }
    if (walkingDistanceMeters.present) {
      map['walking_distance_meters'] = Variable<int>(
        walkingDistanceMeters.value,
      );
    }
    if (resolvedMeters.present) {
      map['resolved_meters'] = Variable<int>(resolvedMeters.value);
    }
    if (flaggedPace.present) {
      map['flagged_pace'] = Variable<int>(flaggedPace.value);
    }
    if (syncedAt.present) {
      map['synced_at'] = Variable<String>(syncedAt.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('StepIntervalRecordsCompanion(')
          ..write('id: $id, ')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('intervalStart: $intervalStart, ')
          ..write('intervalEnd: $intervalEnd, ')
          ..write('steps: $steps, ')
          ..write('walkingDistanceMeters: $walkingDistanceMeters, ')
          ..write('resolvedMeters: $resolvedMeters, ')
          ..write('flaggedPace: $flaggedPace, ')
          ..write('syncedAt: $syncedAt')
          ..write(')'))
        .toString();
  }
}

class LockScreenPreferenceRows extends Table
    with TableInfo<LockScreenPreferenceRows, LockScreenPreferenceRowsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  LockScreenPreferenceRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> enabled = GeneratedColumn<int>(
    'enabled',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (enabled IN (0, 1))',
  );
  @override
  List<GeneratedColumn> get $columns => [ownerId, enabled];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'lock_screen_preference_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId};
  @override
  LockScreenPreferenceRowsData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return LockScreenPreferenceRowsData(
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      enabled: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}enabled'],
      )!,
    );
  }

  @override
  LockScreenPreferenceRows createAlias(String alias) {
    return LockScreenPreferenceRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(owner_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class LockScreenPreferenceRowsData extends DataClass
    implements Insertable<LockScreenPreferenceRowsData> {
  final String ownerId;
  final int enabled;
  const LockScreenPreferenceRowsData({
    required this.ownerId,
    required this.enabled,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['owner_id'] = Variable<String>(ownerId);
    map['enabled'] = Variable<int>(enabled);
    return map;
  }

  LockScreenPreferenceRowsCompanion toCompanion(bool nullToAbsent) {
    return LockScreenPreferenceRowsCompanion(
      ownerId: Value(ownerId),
      enabled: Value(enabled),
    );
  }

  factory LockScreenPreferenceRowsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return LockScreenPreferenceRowsData(
      ownerId: serializer.fromJson<String>(json['ownerId']),
      enabled: serializer.fromJson<int>(json['enabled']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'ownerId': serializer.toJson<String>(ownerId),
      'enabled': serializer.toJson<int>(enabled),
    };
  }

  LockScreenPreferenceRowsData copyWith({String? ownerId, int? enabled}) =>
      LockScreenPreferenceRowsData(
        ownerId: ownerId ?? this.ownerId,
        enabled: enabled ?? this.enabled,
      );
  LockScreenPreferenceRowsData copyWithCompanion(
    LockScreenPreferenceRowsCompanion data,
  ) {
    return LockScreenPreferenceRowsData(
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      enabled: data.enabled.present ? data.enabled.value : this.enabled,
    );
  }

  @override
  String toString() {
    return (StringBuffer('LockScreenPreferenceRowsData(')
          ..write('ownerId: $ownerId, ')
          ..write('enabled: $enabled')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(ownerId, enabled);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is LockScreenPreferenceRowsData &&
          other.ownerId == this.ownerId &&
          other.enabled == this.enabled);
}

class LockScreenPreferenceRowsCompanion
    extends UpdateCompanion<LockScreenPreferenceRowsData> {
  final Value<String> ownerId;
  final Value<int> enabled;
  final Value<int> rowid;
  const LockScreenPreferenceRowsCompanion({
    this.ownerId = const Value.absent(),
    this.enabled = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  LockScreenPreferenceRowsCompanion.insert({
    required String ownerId,
    required int enabled,
    this.rowid = const Value.absent(),
  }) : ownerId = Value(ownerId),
       enabled = Value(enabled);
  static Insertable<LockScreenPreferenceRowsData> custom({
    Expression<String>? ownerId,
    Expression<int>? enabled,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (ownerId != null) 'owner_id': ownerId,
      if (enabled != null) 'enabled': enabled,
      if (rowid != null) 'rowid': rowid,
    });
  }

  LockScreenPreferenceRowsCompanion copyWith({
    Value<String>? ownerId,
    Value<int>? enabled,
    Value<int>? rowid,
  }) {
    return LockScreenPreferenceRowsCompanion(
      ownerId: ownerId ?? this.ownerId,
      enabled: enabled ?? this.enabled,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (enabled.present) {
      map['enabled'] = Variable<int>(enabled.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('LockScreenPreferenceRowsCompanion(')
          ..write('ownerId: $ownerId, ')
          ..write('enabled: $enabled, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class AchievementUnlockRows extends Table
    with TableInfo<AchievementUnlockRows, AchievementUnlockRowsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  AchievementUnlockRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> achievementId = GeneratedColumn<String>(
    'achievement_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> unlockedLocalDate =
      GeneratedColumn<String>(
        'unlocked_local_date',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    ownerId,
    achievementId,
    unlockedLocalDate,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'achievement_unlock_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {
    ownerId,
    achievementId,
    unlockedLocalDate,
  };
  @override
  AchievementUnlockRowsData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return AchievementUnlockRowsData(
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      achievementId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}achievement_id'],
      )!,
      unlockedLocalDate: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}unlocked_local_date'],
      )!,
    );
  }

  @override
  AchievementUnlockRows createAlias(String alias) {
    return AchievementUnlockRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(owner_id, achievement_id, unlocked_local_date)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class AchievementUnlockRowsData extends DataClass
    implements Insertable<AchievementUnlockRowsData> {
  final String ownerId;
  final String achievementId;
  final String unlockedLocalDate;
  const AchievementUnlockRowsData({
    required this.ownerId,
    required this.achievementId,
    required this.unlockedLocalDate,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['owner_id'] = Variable<String>(ownerId);
    map['achievement_id'] = Variable<String>(achievementId);
    map['unlocked_local_date'] = Variable<String>(unlockedLocalDate);
    return map;
  }

  AchievementUnlockRowsCompanion toCompanion(bool nullToAbsent) {
    return AchievementUnlockRowsCompanion(
      ownerId: Value(ownerId),
      achievementId: Value(achievementId),
      unlockedLocalDate: Value(unlockedLocalDate),
    );
  }

  factory AchievementUnlockRowsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return AchievementUnlockRowsData(
      ownerId: serializer.fromJson<String>(json['ownerId']),
      achievementId: serializer.fromJson<String>(json['achievementId']),
      unlockedLocalDate: serializer.fromJson<String>(json['unlockedLocalDate']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'ownerId': serializer.toJson<String>(ownerId),
      'achievementId': serializer.toJson<String>(achievementId),
      'unlockedLocalDate': serializer.toJson<String>(unlockedLocalDate),
    };
  }

  AchievementUnlockRowsData copyWith({
    String? ownerId,
    String? achievementId,
    String? unlockedLocalDate,
  }) => AchievementUnlockRowsData(
    ownerId: ownerId ?? this.ownerId,
    achievementId: achievementId ?? this.achievementId,
    unlockedLocalDate: unlockedLocalDate ?? this.unlockedLocalDate,
  );
  AchievementUnlockRowsData copyWithCompanion(
    AchievementUnlockRowsCompanion data,
  ) {
    return AchievementUnlockRowsData(
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      achievementId: data.achievementId.present
          ? data.achievementId.value
          : this.achievementId,
      unlockedLocalDate: data.unlockedLocalDate.present
          ? data.unlockedLocalDate.value
          : this.unlockedLocalDate,
    );
  }

  @override
  String toString() {
    return (StringBuffer('AchievementUnlockRowsData(')
          ..write('ownerId: $ownerId, ')
          ..write('achievementId: $achievementId, ')
          ..write('unlockedLocalDate: $unlockedLocalDate')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(ownerId, achievementId, unlockedLocalDate);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AchievementUnlockRowsData &&
          other.ownerId == this.ownerId &&
          other.achievementId == this.achievementId &&
          other.unlockedLocalDate == this.unlockedLocalDate);
}

class AchievementUnlockRowsCompanion
    extends UpdateCompanion<AchievementUnlockRowsData> {
  final Value<String> ownerId;
  final Value<String> achievementId;
  final Value<String> unlockedLocalDate;
  final Value<int> rowid;
  const AchievementUnlockRowsCompanion({
    this.ownerId = const Value.absent(),
    this.achievementId = const Value.absent(),
    this.unlockedLocalDate = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  AchievementUnlockRowsCompanion.insert({
    required String ownerId,
    required String achievementId,
    required String unlockedLocalDate,
    this.rowid = const Value.absent(),
  }) : ownerId = Value(ownerId),
       achievementId = Value(achievementId),
       unlockedLocalDate = Value(unlockedLocalDate);
  static Insertable<AchievementUnlockRowsData> custom({
    Expression<String>? ownerId,
    Expression<String>? achievementId,
    Expression<String>? unlockedLocalDate,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (ownerId != null) 'owner_id': ownerId,
      if (achievementId != null) 'achievement_id': achievementId,
      if (unlockedLocalDate != null) 'unlocked_local_date': unlockedLocalDate,
      if (rowid != null) 'rowid': rowid,
    });
  }

  AchievementUnlockRowsCompanion copyWith({
    Value<String>? ownerId,
    Value<String>? achievementId,
    Value<String>? unlockedLocalDate,
    Value<int>? rowid,
  }) {
    return AchievementUnlockRowsCompanion(
      ownerId: ownerId ?? this.ownerId,
      achievementId: achievementId ?? this.achievementId,
      unlockedLocalDate: unlockedLocalDate ?? this.unlockedLocalDate,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (achievementId.present) {
      map['achievement_id'] = Variable<String>(achievementId.value);
    }
    if (unlockedLocalDate.present) {
      map['unlocked_local_date'] = Variable<String>(unlockedLocalDate.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('AchievementUnlockRowsCompanion(')
          ..write('ownerId: $ownerId, ')
          ..write('achievementId: $achievementId, ')
          ..write('unlockedLocalDate: $unlockedLocalDate, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class UserPreferenceRows extends Table
    with TableInfo<UserPreferenceRows, UserPreferenceRowsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  UserPreferenceRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> localeCode = GeneratedColumn<String>(
    'locale_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> themeOverride = GeneratedColumn<String>(
    'theme_override',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> backgroundMusicEnabled = GeneratedColumn<int>(
    'background_music_enabled',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT 0 CHECK (background_music_enabled IN (0, 1))',
  );
  late final GeneratedColumn<int> showFriendsOnMap = GeneratedColumn<int>(
    'show_friends_on_map',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT 0 CHECK (show_friends_on_map IN (0, 1))',
  );
  @override
  List<GeneratedColumn> get $columns => [
    ownerId,
    localeCode,
    themeOverride,
    backgroundMusicEnabled,
    showFriendsOnMap,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'user_preference_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId};
  @override
  UserPreferenceRowsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return UserPreferenceRowsData(
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      localeCode: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}locale_code'],
      ),
      themeOverride: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}theme_override'],
      ),
      backgroundMusicEnabled: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}background_music_enabled'],
      )!,
      showFriendsOnMap: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}show_friends_on_map'],
      )!,
    );
  }

  @override
  UserPreferenceRows createAlias(String alias) {
    return UserPreferenceRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(owner_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class UserPreferenceRowsData extends DataClass
    implements Insertable<UserPreferenceRowsData> {
  final String ownerId;
  final String? localeCode;
  final String? themeOverride;
  final int backgroundMusicEnabled;
  final int showFriendsOnMap;
  const UserPreferenceRowsData({
    required this.ownerId,
    this.localeCode,
    this.themeOverride,
    required this.backgroundMusicEnabled,
    required this.showFriendsOnMap,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['owner_id'] = Variable<String>(ownerId);
    if (!nullToAbsent || localeCode != null) {
      map['locale_code'] = Variable<String>(localeCode);
    }
    if (!nullToAbsent || themeOverride != null) {
      map['theme_override'] = Variable<String>(themeOverride);
    }
    map['background_music_enabled'] = Variable<int>(backgroundMusicEnabled);
    map['show_friends_on_map'] = Variable<int>(showFriendsOnMap);
    return map;
  }

  UserPreferenceRowsCompanion toCompanion(bool nullToAbsent) {
    return UserPreferenceRowsCompanion(
      ownerId: Value(ownerId),
      localeCode: localeCode == null && nullToAbsent
          ? const Value.absent()
          : Value(localeCode),
      themeOverride: themeOverride == null && nullToAbsent
          ? const Value.absent()
          : Value(themeOverride),
      backgroundMusicEnabled: Value(backgroundMusicEnabled),
      showFriendsOnMap: Value(showFriendsOnMap),
    );
  }

  factory UserPreferenceRowsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return UserPreferenceRowsData(
      ownerId: serializer.fromJson<String>(json['ownerId']),
      localeCode: serializer.fromJson<String?>(json['localeCode']),
      themeOverride: serializer.fromJson<String?>(json['themeOverride']),
      backgroundMusicEnabled: serializer.fromJson<int>(
        json['backgroundMusicEnabled'],
      ),
      showFriendsOnMap: serializer.fromJson<int>(json['showFriendsOnMap']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'ownerId': serializer.toJson<String>(ownerId),
      'localeCode': serializer.toJson<String?>(localeCode),
      'themeOverride': serializer.toJson<String?>(themeOverride),
      'backgroundMusicEnabled': serializer.toJson<int>(
        backgroundMusicEnabled,
      ),
      'showFriendsOnMap': serializer.toJson<int>(showFriendsOnMap),
    };
  }

  UserPreferenceRowsData copyWith({
    String? ownerId,
    Value<String?> localeCode = const Value.absent(),
    Value<String?> themeOverride = const Value.absent(),
    int? backgroundMusicEnabled,
    int? showFriendsOnMap,
  }) => UserPreferenceRowsData(
    ownerId: ownerId ?? this.ownerId,
    localeCode: localeCode.present ? localeCode.value : this.localeCode,
    themeOverride: themeOverride.present
        ? themeOverride.value
        : this.themeOverride,
    backgroundMusicEnabled:
        backgroundMusicEnabled ?? this.backgroundMusicEnabled,
    showFriendsOnMap: showFriendsOnMap ?? this.showFriendsOnMap,
  );
  UserPreferenceRowsData copyWithCompanion(UserPreferenceRowsCompanion data) {
    return UserPreferenceRowsData(
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      localeCode: data.localeCode.present
          ? data.localeCode.value
          : this.localeCode,
      themeOverride: data.themeOverride.present
          ? data.themeOverride.value
          : this.themeOverride,
      backgroundMusicEnabled: data.backgroundMusicEnabled.present
          ? data.backgroundMusicEnabled.value
          : this.backgroundMusicEnabled,
      showFriendsOnMap: data.showFriendsOnMap.present
          ? data.showFriendsOnMap.value
          : this.showFriendsOnMap,
    );
  }

  @override
  String toString() {
    return (StringBuffer('UserPreferenceRowsData(')
          ..write('ownerId: $ownerId, ')
          ..write('localeCode: $localeCode, ')
          ..write('themeOverride: $themeOverride, ')
          ..write('backgroundMusicEnabled: $backgroundMusicEnabled, ')
          ..write('showFriendsOnMap: $showFriendsOnMap')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    ownerId,
    localeCode,
    themeOverride,
    backgroundMusicEnabled,
    showFriendsOnMap,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is UserPreferenceRowsData &&
          other.ownerId == this.ownerId &&
          other.localeCode == this.localeCode &&
          other.themeOverride == this.themeOverride &&
          other.backgroundMusicEnabled == this.backgroundMusicEnabled &&
          other.showFriendsOnMap == this.showFriendsOnMap);
}

class UserPreferenceRowsCompanion
    extends UpdateCompanion<UserPreferenceRowsData> {
  final Value<String> ownerId;
  final Value<String?> localeCode;
  final Value<String?> themeOverride;
  final Value<int> backgroundMusicEnabled;
  final Value<int> showFriendsOnMap;
  final Value<int> rowid;
  const UserPreferenceRowsCompanion({
    this.ownerId = const Value.absent(),
    this.localeCode = const Value.absent(),
    this.themeOverride = const Value.absent(),
    this.backgroundMusicEnabled = const Value.absent(),
    this.showFriendsOnMap = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  UserPreferenceRowsCompanion.insert({
    required String ownerId,
    this.localeCode = const Value.absent(),
    this.themeOverride = const Value.absent(),
    this.backgroundMusicEnabled = const Value.absent(),
    this.showFriendsOnMap = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : ownerId = Value(ownerId);
  static Insertable<UserPreferenceRowsData> custom({
    Expression<String>? ownerId,
    Expression<String>? localeCode,
    Expression<String>? themeOverride,
    Expression<int>? backgroundMusicEnabled,
    Expression<int>? showFriendsOnMap,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (ownerId != null) 'owner_id': ownerId,
      if (localeCode != null) 'locale_code': localeCode,
      if (themeOverride != null) 'theme_override': themeOverride,
      if (backgroundMusicEnabled != null)
        'background_music_enabled': backgroundMusicEnabled,
      if (showFriendsOnMap != null) 'show_friends_on_map': showFriendsOnMap,
      if (rowid != null) 'rowid': rowid,
    });
  }

  UserPreferenceRowsCompanion copyWith({
    Value<String>? ownerId,
    Value<String?>? localeCode,
    Value<String?>? themeOverride,
    Value<int>? backgroundMusicEnabled,
    Value<int>? showFriendsOnMap,
    Value<int>? rowid,
  }) {
    return UserPreferenceRowsCompanion(
      ownerId: ownerId ?? this.ownerId,
      localeCode: localeCode ?? this.localeCode,
      themeOverride: themeOverride ?? this.themeOverride,
      backgroundMusicEnabled:
          backgroundMusicEnabled ?? this.backgroundMusicEnabled,
      showFriendsOnMap: showFriendsOnMap ?? this.showFriendsOnMap,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (localeCode.present) {
      map['locale_code'] = Variable<String>(localeCode.value);
    }
    if (themeOverride.present) {
      map['theme_override'] = Variable<String>(themeOverride.value);
    }
    if (backgroundMusicEnabled.present) {
      map['background_music_enabled'] = Variable<int>(
        backgroundMusicEnabled.value,
      );
    }
    if (showFriendsOnMap.present) {
      map['show_friends_on_map'] = Variable<int>(showFriendsOnMap.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('UserPreferenceRowsCompanion(')
          ..write('ownerId: $ownerId, ')
          ..write('localeCode: $localeCode, ')
          ..write('themeOverride: $themeOverride, ')
          ..write('backgroundMusicEnabled: $backgroundMusicEnabled, ')
          ..write('showFriendsOnMap: $showFriendsOnMap, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV4 extends GeneratedDatabase {
  DatabaseAtV4(QueryExecutor e) : super(e);
  late final SelectedQuestRows selectedQuestRows = SelectedQuestRows(this);
  late final StepIntervalRecords stepIntervalRecords = StepIntervalRecords(
    this,
  );
  late final LockScreenPreferenceRows lockScreenPreferenceRows =
      LockScreenPreferenceRows(this);
  late final AchievementUnlockRows achievementUnlockRows =
      AchievementUnlockRows(this);
  late final UserPreferenceRows userPreferenceRows = UserPreferenceRows(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    selectedQuestRows,
    stepIntervalRecords,
    lockScreenPreferenceRows,
    achievementUnlockRows,
    userPreferenceRows,
  ];
  @override
  int get schemaVersion => 4;
  @override
  DriftDatabaseOptions get options =>
      const DriftDatabaseOptions(storeDateTimeAsText: true);
}
