// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class SelectedQuestRows extends Table
    with TableInfo<SelectedQuestRows, SelectedQuestRowsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  SelectedQuestRows(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> journeyId = GeneratedColumn<String>(
    'journey_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> startedAt = GeneratedColumn<String>(
    'started_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [ownerId, journeyId, startedAt];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'selected_quest_rows';
  @override
  Set<GeneratedColumn> get $primaryKey => {ownerId};
  @override
  SelectedQuestRowsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return SelectedQuestRowsData(
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      journeyId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}journey_id'],
      )!,
      startedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}started_at'],
      )!,
    );
  }

  @override
  SelectedQuestRows createAlias(String alias) {
    return SelectedQuestRows(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(owner_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class SelectedQuestRowsData extends DataClass
    implements Insertable<SelectedQuestRowsData> {
  final String ownerId;
  final String journeyId;
  final String startedAt;
  const SelectedQuestRowsData({
    required this.ownerId,
    required this.journeyId,
    required this.startedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['owner_id'] = Variable<String>(ownerId);
    map['journey_id'] = Variable<String>(journeyId);
    map['started_at'] = Variable<String>(startedAt);
    return map;
  }

  SelectedQuestRowsCompanion toCompanion(bool nullToAbsent) {
    return SelectedQuestRowsCompanion(
      ownerId: Value(ownerId),
      journeyId: Value(journeyId),
      startedAt: Value(startedAt),
    );
  }

  factory SelectedQuestRowsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return SelectedQuestRowsData(
      ownerId: serializer.fromJson<String>(json['ownerId']),
      journeyId: serializer.fromJson<String>(json['journeyId']),
      startedAt: serializer.fromJson<String>(json['startedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'ownerId': serializer.toJson<String>(ownerId),
      'journeyId': serializer.toJson<String>(journeyId),
      'startedAt': serializer.toJson<String>(startedAt),
    };
  }

  SelectedQuestRowsData copyWith({
    String? ownerId,
    String? journeyId,
    String? startedAt,
  }) => SelectedQuestRowsData(
    ownerId: ownerId ?? this.ownerId,
    journeyId: journeyId ?? this.journeyId,
    startedAt: startedAt ?? this.startedAt,
  );
  SelectedQuestRowsData copyWithCompanion(SelectedQuestRowsCompanion data) {
    return SelectedQuestRowsData(
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      journeyId: data.journeyId.present ? data.journeyId.value : this.journeyId,
      startedAt: data.startedAt.present ? data.startedAt.value : this.startedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('SelectedQuestRowsData(')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('startedAt: $startedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(ownerId, journeyId, startedAt);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is SelectedQuestRowsData &&
          other.ownerId == this.ownerId &&
          other.journeyId == this.journeyId &&
          other.startedAt == this.startedAt);
}

class SelectedQuestRowsCompanion
    extends UpdateCompanion<SelectedQuestRowsData> {
  final Value<String> ownerId;
  final Value<String> journeyId;
  final Value<String> startedAt;
  final Value<int> rowid;
  const SelectedQuestRowsCompanion({
    this.ownerId = const Value.absent(),
    this.journeyId = const Value.absent(),
    this.startedAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  SelectedQuestRowsCompanion.insert({
    required String ownerId,
    required String journeyId,
    required String startedAt,
    this.rowid = const Value.absent(),
  }) : ownerId = Value(ownerId),
       journeyId = Value(journeyId),
       startedAt = Value(startedAt);
  static Insertable<SelectedQuestRowsData> custom({
    Expression<String>? ownerId,
    Expression<String>? journeyId,
    Expression<String>? startedAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (ownerId != null) 'owner_id': ownerId,
      if (journeyId != null) 'journey_id': journeyId,
      if (startedAt != null) 'started_at': startedAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  SelectedQuestRowsCompanion copyWith({
    Value<String>? ownerId,
    Value<String>? journeyId,
    Value<String>? startedAt,
    Value<int>? rowid,
  }) {
    return SelectedQuestRowsCompanion(
      ownerId: ownerId ?? this.ownerId,
      journeyId: journeyId ?? this.journeyId,
      startedAt: startedAt ?? this.startedAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (journeyId.present) {
      map['journey_id'] = Variable<String>(journeyId.value);
    }
    if (startedAt.present) {
      map['started_at'] = Variable<String>(startedAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('SelectedQuestRowsCompanion(')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('startedAt: $startedAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class StepIntervalRecords extends Table
    with TableInfo<StepIntervalRecords, StepIntervalRecordsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  StepIntervalRecords(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id',
    aliasedName,
    false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
  );
  late final GeneratedColumn<String> ownerId = GeneratedColumn<String>(
    'owner_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> journeyId = GeneratedColumn<String>(
    'journey_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> intervalStart = GeneratedColumn<String>(
    'interval_start',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> intervalEnd = GeneratedColumn<String>(
    'interval_end',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> steps = GeneratedColumn<int>(
    'steps',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> walkingDistanceMeters = GeneratedColumn<int>(
    'walking_distance_meters',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> resolvedMeters = GeneratedColumn<int>(
    'resolved_meters',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> flaggedPace = GeneratedColumn<int>(
    'flagged_pace',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0 CHECK (flagged_pace IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> syncedAt = GeneratedColumn<String>(
    'synced_at',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    ownerId,
    journeyId,
    intervalStart,
    intervalEnd,
    steps,
    walkingDistanceMeters,
    resolvedMeters,
    flaggedPace,
    syncedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'step_interval_records';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {ownerId, journeyId, intervalStart},
  ];
  @override
  StepIntervalRecordsData map(
    Map<String, dynamic> data, {
    String? tablePrefix,
  }) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return StepIntervalRecordsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}id'],
      )!,
      ownerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}owner_id'],
      )!,
      journeyId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}journey_id'],
      )!,
      intervalStart: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}interval_start'],
      )!,
      intervalEnd: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}interval_end'],
      )!,
      steps: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}steps'],
      )!,
      walkingDistanceMeters: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}walking_distance_meters'],
      ),
      resolvedMeters: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}resolved_meters'],
      )!,
      flaggedPace: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}flagged_pace'],
      )!,
      syncedAt: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}synced_at'],
      )!,
    );
  }

  @override
  StepIntervalRecords createAlias(String alias) {
    return StepIntervalRecords(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'UNIQUE(owner_id, journey_id, interval_start)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class StepIntervalRecordsData extends DataClass
    implements Insertable<StepIntervalRecordsData> {
  final int id;
  final String ownerId;
  final String journeyId;
  final String intervalStart;
  final String intervalEnd;
  final int steps;
  final int? walkingDistanceMeters;
  final int resolvedMeters;
  final int flaggedPace;
  final String syncedAt;
  const StepIntervalRecordsData({
    required this.id,
    required this.ownerId,
    required this.journeyId,
    required this.intervalStart,
    required this.intervalEnd,
    required this.steps,
    this.walkingDistanceMeters,
    required this.resolvedMeters,
    required this.flaggedPace,
    required this.syncedAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<int>(id);
    map['owner_id'] = Variable<String>(ownerId);
    map['journey_id'] = Variable<String>(journeyId);
    map['interval_start'] = Variable<String>(intervalStart);
    map['interval_end'] = Variable<String>(intervalEnd);
    map['steps'] = Variable<int>(steps);
    if (!nullToAbsent || walkingDistanceMeters != null) {
      map['walking_distance_meters'] = Variable<int>(walkingDistanceMeters);
    }
    map['resolved_meters'] = Variable<int>(resolvedMeters);
    map['flagged_pace'] = Variable<int>(flaggedPace);
    map['synced_at'] = Variable<String>(syncedAt);
    return map;
  }

  StepIntervalRecordsCompanion toCompanion(bool nullToAbsent) {
    return StepIntervalRecordsCompanion(
      id: Value(id),
      ownerId: Value(ownerId),
      journeyId: Value(journeyId),
      intervalStart: Value(intervalStart),
      intervalEnd: Value(intervalEnd),
      steps: Value(steps),
      walkingDistanceMeters: walkingDistanceMeters == null && nullToAbsent
          ? const Value.absent()
          : Value(walkingDistanceMeters),
      resolvedMeters: Value(resolvedMeters),
      flaggedPace: Value(flaggedPace),
      syncedAt: Value(syncedAt),
    );
  }

  factory StepIntervalRecordsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return StepIntervalRecordsData(
      id: serializer.fromJson<int>(json['id']),
      ownerId: serializer.fromJson<String>(json['ownerId']),
      journeyId: serializer.fromJson<String>(json['journeyId']),
      intervalStart: serializer.fromJson<String>(json['intervalStart']),
      intervalEnd: serializer.fromJson<String>(json['intervalEnd']),
      steps: serializer.fromJson<int>(json['steps']),
      walkingDistanceMeters: serializer.fromJson<int?>(
        json['walkingDistanceMeters'],
      ),
      resolvedMeters: serializer.fromJson<int>(json['resolvedMeters']),
      flaggedPace: serializer.fromJson<int>(json['flaggedPace']),
      syncedAt: serializer.fromJson<String>(json['syncedAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<int>(id),
      'ownerId': serializer.toJson<String>(ownerId),
      'journeyId': serializer.toJson<String>(journeyId),
      'intervalStart': serializer.toJson<String>(intervalStart),
      'intervalEnd': serializer.toJson<String>(intervalEnd),
      'steps': serializer.toJson<int>(steps),
      'walkingDistanceMeters': serializer.toJson<int?>(walkingDistanceMeters),
      'resolvedMeters': serializer.toJson<int>(resolvedMeters),
      'flaggedPace': serializer.toJson<int>(flaggedPace),
      'syncedAt': serializer.toJson<String>(syncedAt),
    };
  }

  StepIntervalRecordsData copyWith({
    int? id,
    String? ownerId,
    String? journeyId,
    String? intervalStart,
    String? intervalEnd,
    int? steps,
    Value<int?> walkingDistanceMeters = const Value.absent(),
    int? resolvedMeters,
    int? flaggedPace,
    String? syncedAt,
  }) => StepIntervalRecordsData(
    id: id ?? this.id,
    ownerId: ownerId ?? this.ownerId,
    journeyId: journeyId ?? this.journeyId,
    intervalStart: intervalStart ?? this.intervalStart,
    intervalEnd: intervalEnd ?? this.intervalEnd,
    steps: steps ?? this.steps,
    walkingDistanceMeters: walkingDistanceMeters.present
        ? walkingDistanceMeters.value
        : this.walkingDistanceMeters,
    resolvedMeters: resolvedMeters ?? this.resolvedMeters,
    flaggedPace: flaggedPace ?? this.flaggedPace,
    syncedAt: syncedAt ?? this.syncedAt,
  );
  StepIntervalRecordsData copyWithCompanion(StepIntervalRecordsCompanion data) {
    return StepIntervalRecordsData(
      id: data.id.present ? data.id.value : this.id,
      ownerId: data.ownerId.present ? data.ownerId.value : this.ownerId,
      journeyId: data.journeyId.present ? data.journeyId.value : this.journeyId,
      intervalStart: data.intervalStart.present
          ? data.intervalStart.value
          : this.intervalStart,
      intervalEnd: data.intervalEnd.present
          ? data.intervalEnd.value
          : this.intervalEnd,
      steps: data.steps.present ? data.steps.value : this.steps,
      walkingDistanceMeters: data.walkingDistanceMeters.present
          ? data.walkingDistanceMeters.value
          : this.walkingDistanceMeters,
      resolvedMeters: data.resolvedMeters.present
          ? data.resolvedMeters.value
          : this.resolvedMeters,
      flaggedPace: data.flaggedPace.present
          ? data.flaggedPace.value
          : this.flaggedPace,
      syncedAt: data.syncedAt.present ? data.syncedAt.value : this.syncedAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('StepIntervalRecordsData(')
          ..write('id: $id, ')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('intervalStart: $intervalStart, ')
          ..write('intervalEnd: $intervalEnd, ')
          ..write('steps: $steps, ')
          ..write('walkingDistanceMeters: $walkingDistanceMeters, ')
          ..write('resolvedMeters: $resolvedMeters, ')
          ..write('flaggedPace: $flaggedPace, ')
          ..write('syncedAt: $syncedAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    ownerId,
    journeyId,
    intervalStart,
    intervalEnd,
    steps,
    walkingDistanceMeters,
    resolvedMeters,
    flaggedPace,
    syncedAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is StepIntervalRecordsData &&
          other.id == this.id &&
          other.ownerId == this.ownerId &&
          other.journeyId == this.journeyId &&
          other.intervalStart == this.intervalStart &&
          other.intervalEnd == this.intervalEnd &&
          other.steps == this.steps &&
          other.walkingDistanceMeters == this.walkingDistanceMeters &&
          other.resolvedMeters == this.resolvedMeters &&
          other.flaggedPace == this.flaggedPace &&
          other.syncedAt == this.syncedAt);
}

class StepIntervalRecordsCompanion
    extends UpdateCompanion<StepIntervalRecordsData> {
  final Value<int> id;
  final Value<String> ownerId;
  final Value<String> journeyId;
  final Value<String> intervalStart;
  final Value<String> intervalEnd;
  final Value<int> steps;
  final Value<int?> walkingDistanceMeters;
  final Value<int> resolvedMeters;
  final Value<int> flaggedPace;
  final Value<String> syncedAt;
  const StepIntervalRecordsCompanion({
    this.id = const Value.absent(),
    this.ownerId = const Value.absent(),
    this.journeyId = const Value.absent(),
    this.intervalStart = const Value.absent(),
    this.intervalEnd = const Value.absent(),
    this.steps = const Value.absent(),
    this.walkingDistanceMeters = const Value.absent(),
    this.resolvedMeters = const Value.absent(),
    this.flaggedPace = const Value.absent(),
    this.syncedAt = const Value.absent(),
  });
  StepIntervalRecordsCompanion.insert({
    this.id = const Value.absent(),
    required String ownerId,
    required String journeyId,
    required String intervalStart,
    required String intervalEnd,
    required int steps,
    this.walkingDistanceMeters = const Value.absent(),
    required int resolvedMeters,
    this.flaggedPace = const Value.absent(),
    required String syncedAt,
  }) : ownerId = Value(ownerId),
       journeyId = Value(journeyId),
       intervalStart = Value(intervalStart),
       intervalEnd = Value(intervalEnd),
       steps = Value(steps),
       resolvedMeters = Value(resolvedMeters),
       syncedAt = Value(syncedAt);
  static Insertable<StepIntervalRecordsData> custom({
    Expression<int>? id,
    Expression<String>? ownerId,
    Expression<String>? journeyId,
    Expression<String>? intervalStart,
    Expression<String>? intervalEnd,
    Expression<int>? steps,
    Expression<int>? walkingDistanceMeters,
    Expression<int>? resolvedMeters,
    Expression<int>? flaggedPace,
    Expression<String>? syncedAt,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (ownerId != null) 'owner_id': ownerId,
      if (journeyId != null) 'journey_id': journeyId,
      if (intervalStart != null) 'interval_start': intervalStart,
      if (intervalEnd != null) 'interval_end': intervalEnd,
      if (steps != null) 'steps': steps,
      if (walkingDistanceMeters != null)
        'walking_distance_meters': walkingDistanceMeters,
      if (resolvedMeters != null) 'resolved_meters': resolvedMeters,
      if (flaggedPace != null) 'flagged_pace': flaggedPace,
      if (syncedAt != null) 'synced_at': syncedAt,
    });
  }

  StepIntervalRecordsCompanion copyWith({
    Value<int>? id,
    Value<String>? ownerId,
    Value<String>? journeyId,
    Value<String>? intervalStart,
    Value<String>? intervalEnd,
    Value<int>? steps,
    Value<int?>? walkingDistanceMeters,
    Value<int>? resolvedMeters,
    Value<int>? flaggedPace,
    Value<String>? syncedAt,
  }) {
    return StepIntervalRecordsCompanion(
      id: id ?? this.id,
      ownerId: ownerId ?? this.ownerId,
      journeyId: journeyId ?? this.journeyId,
      intervalStart: intervalStart ?? this.intervalStart,
      intervalEnd: intervalEnd ?? this.intervalEnd,
      steps: steps ?? this.steps,
      walkingDistanceMeters:
          walkingDistanceMeters ?? this.walkingDistanceMeters,
      resolvedMeters: resolvedMeters ?? this.resolvedMeters,
      flaggedPace: flaggedPace ?? this.flaggedPace,
      syncedAt: syncedAt ?? this.syncedAt,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<int>(id.value);
    }
    if (ownerId.present) {
      map['owner_id'] = Variable<String>(ownerId.value);
    }
    if (journeyId.present) {
      map['journey_id'] = Variable<String>(journeyId.value);
    }
    if (intervalStart.present) {
      map['interval_start'] = Variable<String>(intervalStart.value);
    }
    if (intervalEnd.present) {
      map['interval_end'] = Variable<String>(intervalEnd.value);
    }
    if (steps.present) {
      map['steps'] = Variable<int>(steps.value);
    }
    if (walkingDistanceMeters.present) {
      map['walking_distance_meters'] = Variable<int>(
        walkingDistanceMeters.value,
      );
    }
    if (resolvedMeters.present) {
      map['resolved_meters'] = Variable<int>(resolvedMeters.value);
    }
    if (flaggedPace.present) {
      map['flagged_pace'] = Variable<int>(flaggedPace.value);
    }
    if (syncedAt.present) {
      map['synced_at'] = Variable<String>(syncedAt.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('StepIntervalRecordsCompanion(')
          ..write('id: $id, ')
          ..write('ownerId: $ownerId, ')
          ..write('journeyId: $journeyId, ')
          ..write('intervalStart: $intervalStart, ')
          ..write('intervalEnd: $intervalEnd, ')
          ..write('steps: $steps, ')
          ..write('walkingDistanceMeters: $walkingDistanceMeters, ')
          ..write('resolvedMeters: $resolvedMeters, ')
          ..write('flaggedPace: $flaggedPace, ')
          ..write('syncedAt: $syncedAt')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final SelectedQuestRows selectedQuestRows = SelectedQuestRows(this);
  late final StepIntervalRecords stepIntervalRecords = StepIntervalRecords(
    this,
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    selectedQuestRows,
    stepIntervalRecords,
  ];
  @override
  int get schemaVersion => 1;
  @override
  DriftDatabaseOptions get options =>
      const DriftDatabaseOptions(storeDateTimeAsText: true);
}
